name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - stable
      - v*

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # This is the "main" test suite, which tests a large number of different
  # versions of default compilers and Python versions in GitHub Actions.
  standard:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-2022, macos-latest]
        python:
        - '3.8'
        - '3.9'
        - '3.10'

    name: "Python ${{ matrix.python }} / ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.12

    - name: Install Python dependencies
      run: |
        python -m pip install pytest pytest-github-actions-annotate-failures numpy

    - name: Configure
      run: >
        cmake -S . -B build "-DPython_EXECUTABLE=$(python3 -c 'import sys; print(sys.executable)')"

    - name: Build C++
      run: cmake --build build -j 2

    - name: Run tests
      run: >
        cd build;
        python -m pytest
